name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          npm install
          npm run-script lint

  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@5e13dcb03778dc9a47bd0adbd84c48392b32cd46
    with:
      dockerImage: gridsuite/oidc-mock-server
      dockerUsername: gridsuiteci
      dockerRoUsername: rogridsuiteci
      eventType: oidc_mock_server_updated
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      docker-ro-token: ${{ secrets.DOCKERHUB_RO_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
